const ENV = process.env.ENV;
const DEVELOPMENT_HOST = process.env.DEVELOPMENT_HOST;
const DEVELOPMENT_USER = process.env.DEVELOPMENT_USER;
const DEVELOPMENT_PASSWORD = process.env.DEVELOPMENT_PASSWORD;
const DEVELOPMENT_DATABASE = process.env.DEVELOPMENT_DATABASE;
const PRODUCTION_HOST = process.env.PRODUCTION_HOST;
const PRODUCTION_USER = process.env.PRODUCTION_USER;
const PRODUCTION_PASSWORD = process.env.PRODUCTION_PASSWORD;
const PRODUCTION_DATABASE = process.env.PRODUCTION_DATABASE;

module.exports = {
  ENV,
  DEVELOPMENT_HOST,
  DEVELOPMENT_USER,
  DEVELOPMENT_PASSWORD,
  DEVELOPMENT_DATABASE,
  PRODUCTION_HOST,
  PRODUCTION_USER,
  PRODUCTION_PASSWORD,
  PRODUCTION_DATABASE,
};
